### ISSUE TITLE
Image ViT feature dimensions: 1x1024 v.s. 192x1280

### ISSUE THREAD

**Issue by zehongs** [yohanshin/WHAM#18]
Hi @yohanshin ,  I'm here again with some new questions😄
Which HMR2.0 variant (a or b) are you using to extract ViT features? I've also noticed that both variants yield a feature dimension of 1280 at the end of the image backbone. More specifically, the input is 256 x 192 x 3, while the output is (16*12) x 1280. "I am confused as to why your pre-saved ViT feature for an image is 1 x 1024. Could you give me some advice?

**Comment by yohanshin** [comment]
Hi @zehongs , I am happy to have all your questions and thanks for asking :).

I used HMR2.0 (a) for the feature extraction. I haven't tested with version b yet. 

Yes as you mentioned, the input is 256 x 192 (the model takes 256 x 256 as input, but ignores the first and the last 32 columns in the forward step). I think (16x12)x1280 is the shape of `conditioning_feats` in [line](https://github.com/shubham-goel/4D-Humans/blob/a0def798c7eac811a63c8220fcc22d983b39785e/hmr2/models/hmr2.py#L105). Instead of using this , we used `token_out`, which is the output of the transformer decoder [here](https://github.com/shubham-goel/4D-Humans/blob/a0def798c7eac811a63c8220fcc22d983b39785e/hmr2/models/heads/smpl_head.py#L85). Here is my forward function of HMR2.0 model:


```
def forward(self, x, encode=False, **kwargs):
    """
    Run a forward step of the network
    Args:
        x (torch.Tensor): Cropped and normalized image (batch, 256, 256, 3)
        encode (bool): whether to only extract feature or not
    Returns:
        if encode is True, output 1024 dimensional feature. 
        if encode is False, output SMPL parameters and weak-perspective camera translation.
    """
  
    # Use RGB image as input
    batch_size = x.shape[0]
  
    # Compute conditioning features using the backbone
    # if using ViT backbone, we need to use a different aspect ratio
    conditioning_feats = self.backbone(x[:,:,:,32:-32])
    if encode:
        conditioning_feats = einops.rearrange(conditioning_feats, 'b c h w -> b (h w) c')
        token = torch.zeros(batch_size, 1, 1).to(x.device)
        token_out = self.smpl_head.transformer(token, context=conditioning_feats)
        return token_out.squeeze(1)
  
    pred_smpl_params, pred_cam, _ = self.smpl_head(conditioning_feats)
  
    # Compute model vertices, joints and the projected joints
    pred_smpl_params['global_orient'] = pred_smpl_params['global_orient'].reshape(batch_size, -1, 3, 3)
    pred_smpl_params['body_pose'] = pred_smpl_params['body_pose'].reshape(batch_size, -1, 3, 3)
    pred_smpl_params['betas'] = pred_smpl_params['betas'].reshape(batch_size, -1)
    return pred_smpl_params['global_orient'], pred_smpl_params['body_pose'], pred_smpl_params['betas'], pred_cam

```
