### ISSUE TITLE
How to obtain camera angle velocity?

### ISSUE THREAD

**Issue by xjwxjw** [yohanshin/WHAM#3]
![image](https://github.com/yohanshin/WHAM/assets/23734975/e747e627-63ee-41cc-b389-12f4fa569fb1)
Hi, I would like to run the pre-trained model on in-the-wild videos. I have figured out the meaning of all inputs except "cam_angvel".

**Comment by RohaanA** [comment]
Hi, this is unrelated to your issue but if you are successful can you please fork this repo and add a script to run the model on in the wild videos? (I'd like to run it too but I don't have enough knowledge to do it)

**Comment by yohanshin** [comment]
Hi @xjwxjw , are you trying to run on your custom video? If so, you need to get camera angular velocity by running SLAM beforehand. Once you have `R`, which is the camera to world rotational transformation, over time, you can compute and normalize angular velocity as shown in the code (the figure you uploaded). Note that we follow camera coordinate convention as X-right, Y-down, and Z-forward. 

Hi @RohaanA , we plan to provide a demo script that involves all preprocessing stages (e.g., 2D detection, SLAM, and WHAM), so that you can just upload a video and get world-grounded 3D human motion.

**Comment by lucasjinreal** [comment]
@yohanshin this is nice, we can truely have a offline pipeline solves wild videos and output 3d motions directly.
