### ISSUE TITLE
Question about contact conf?

### ISSUE THREAD

**Issue by dnqf11** [yohanshin/WHAM#36]
Thanks for your great work. Do you have any idea why the foot_contact conf could be lower than 0 or higher than 1. thank you

**Comment by yohanshin** [comment]
Hi @dnqf11 

When we trained the foot-contact probability, we made the final layer directly regress the probability instead of using the SoftMax operation, which enforces the output to be within (0, 1), at the end. This naive design, however, showed quite a robust estimation of the contact but naturally, the layer often outputs a probability that is not within the boundary.
