### ISSUE TITLE
An Immobile person have the pelvis bones that move up/down

### ISSUE THREAD

**Issue by polidox2** [yohanshin/WHAM#54]
Hi,

I noticed that in any video where the person don't move, in WHAM the pelvis is moving and it make the immobile person move down/up sometimes left/right.

This problem is with the pelvis bone, that can't recognize that the person is immobile and not moving.

A sample video is not required, any recorded video of someone not moving foot but only hands will make this bug appear.

Thank you.

**Comment by yohanshin** [comment]
Hi @polidox2 

Thanks for pointing this out. I am not 100% sure about the issue you raised, but WHAM does not always provide perfect estimation (although it shows SOTA performance in benchmarks). I just posted a sample result of a golfer [here](https://github.com/yohanshin/WHAM/issues/39#issuecomment-1931228099). Is this qualitative result aligned with your question?

**Comment by polidox2** [comment]
Thank you for your reply! 
No actually the issue is much more serious than your golfer video.

Specially in long video 30s+

https://github.com/yohanshin/WHAM/assets/29620611/7a685229-4853-4fcb-8d2d-ed1d98d4dbdd

in this video, i am training with my legs but i am immobile, however in WHAM the pelvis is moving very far away and making very unnatural and far movement.


I also recoded my self just speaking with hand movement, but immobile foot however WHAM give this results:

https://github.com/yohanshin/WHAM/assets/29620611/fd6e58ca-4bef-4e62-ae59-a6d6eba74139

i did speed up both videos so you can see how serious it is.

Thank you!

**Comment by yohanshin** [comment]
@polidox2 

Hi, thanks for sharing your results. For the first case, it is because WHAM was not well-trained on those exercise motions and thus, its global motion prediction may be incorrect. For the second video, it's a bit surprising to see those foot sliding even with the static pose. I just searched a speech video with the standing person and I don't see any of foot sliding as below. 

https://github.com/yohanshin/WHAM/assets/46889727/cee499cb-2d84-4333-b600-e9ee65278df3

Did you visualize the global motion? If so, was the camera moving in your case?

**Comment by carlosedubarreto** [comment]
@yohanshin I think @polidox2  was using the addon version I'm making for WHAM.
And after making some tests, I found that using the local parameters (or not the world ones) for translation and pose, and also removing the Z axis of the translation (because it "jitters" like it happens with 4d humans) it presented, at least to me much better and stable results.

here is a sample of the result I"m having (speeding up the timeline)

https://github.com/yohanshin/WHAM/assets/4061130/8545d49b-4b40-4404-9c57-dbf37c0174c1

**Comment by polidox2** [comment]
The issue is because of shrinking see #64

**Comment by tannq-jo** [comment]
Hi @carlosedubarreto, could you clarify what you mean by "removing the Z axis of the translation"? Are you referring to setting the Z component to zero?
