### ISSUE TITLE
Question regarding multi-person videos

### ISSUE THREAD

**Issue by tijiang13** [yohanshin/WHAM#86]
Hi Soyong,

Thanks for the great work! I tested the demo and it worked very well. However, when I tried sequences with multiple people, I noticed that the relative positions seemed a bit strange, and all the people appeared to be jammed at the origin in the first frame. Is this the expected behavior?

<img src="https://github.com/yohanshin/WHAM/assets/15152165/a7625b44-9a56-491a-9df0-dddbf58c1754" width="300">

Best, Tianjian

**Comment by yohanshin** [comment]
Hi @tijiang13 ,

Each person's global translation is initialized with 0s, so it's expected that each subject starts from the origin. Furthermore, since WHAM predicts each subject individually, the predicted people may not stay in the same world coordinates. One easy (?) solution is, 

1. Take one representative subject among the people.
2. Construct the camera frame with respect to the reference subject's motion
3. Re-map other subjects' motion to the reference subject's world frame using camera un-projection.

**Comment by tijiang13** [comment]
Thanks @yohanshin!

I also tried that idea last week, however one problem is that (correct me if I am wrong) when I tried to align one subject's motion (in global coord) with the camera, the alignment of the first frame is decent but it drifts away quickly even when calib is provided -- my thought is that when WHAM predicts the translation (in world coordinate) it did not use the calibration explicitly. Do you think that's expected?

Best, Tianjian

**Comment by yohanshin** [comment]
Yes, since WHAM does not use the SLAM results explicitly, it suffers from drift. I haven't experimented with, but what you can add some post-processing using SLAM results (update the global orientation using the SLAM results and then refine root velocity accordingly). Since SLAM results will be applied equally across subjects, this might be good solution to tie all people into the same coordinate system.

**Comment by tijiang13** [comment]
I was trying that idea too but it appears that the motions (in global coords) become a bit of jittery with further refinement. Perhaps it's just yet another scenario where we need to make trade-off between visual appeal and accuracy. Anyway, thanks @yohanshin for the clarification!
